#exception handling 

a=["python","exception","try and except"]
try:
    for i in range(4):
        print("the index and element of the array is ",i,a[i])
except:
        print("index out of range") 